services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.fastapi
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8080"]
    env_file:
      - ../api/.env
    ports:
      - "8080:8080"
    volumes: []
